name: Run Script in Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-in-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script inside Docker container
        run: |
          bash tools/open.sh \
          bash tools/run_ws.sh