name: Run Script in Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-in-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script inside Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ghvs/pipeline-ros-noetic-ubuntu-20-02 \
            bash tools/run_ws.sh