name: Run Script in Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghvs/pipeline-ros-noetic-ubuntu-20-02:latest
      options: --user root  # sem -it

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update && apt install -y \
            ros-noetic-catkin \
            python3-catkin-tools \
            python3-vcstool

      - name: Configure Catkin workspace
        run: |
          cd src \
          catkin init \
          catkin config --merge-devel \

      - name: Build workspace
        run: |
          bash tools/run_ws.sh